  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: superStructure_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: boom_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: rope_joint

  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: hook_block_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: hook_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
